f=open('file handling replace.txt','w+')
f.write(input('Enter a sentence: '))
f.seek(0)
words=f.read()
l=words.split()
num=l.count('this')
f.close()
f1=open('file handling replace.txt','w+')
f1.write(words.replace('this','that',num))
f1.seek(0)
print(f1.read())
f1.close()